import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export default StyleSheet.create({
  background: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#e8ecf4',
  },
  container: {
    width: '100%',
    maxWidth: 500,
    backgroundColor: '#6699FF',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
  },
  header: {
    fontSize: 28,
    fontWeight: '700',
    color: '#2b2d42',
    marginBottom: 12,
    textAlign: 'center',
  },
  image: {
    width: 220,
    height: 220,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#dcdcdc',
    marginBottom: 10,
  },
  timer: {
    fontSize: 20,
    fontWeight: '600',
    color: '#ff5252',
    marginBottom: 6,
  },
  score: {
    fontSize: 18,
    fontWeight: '600',
    color: '#4caf50',
    marginBottom: 4,
  },
  selectedLetters: {
    fontSize: 26,
    fontWeight: '600',
    color: '#333',
    letterSpacing: 3,
    marginVertical: 10,
    textAlign: 'center',
  },
  controlButton: {
    backgroundColor: '#673ab7',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 10,
    marginHorizontal: 6,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 3,
  },
  letterContainer: {
    marginTop: 24,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  letterButton: {
    backgroundColor: '#f5f5f5',
    paddingVertical: 14,
    paddingHorizontal: 16,
    margin: 6,
    borderRadius: 10,
    minWidth: width / 6.5,
    alignItems: 'center',
    shadowColor: '#aaa',
    shadowOffset: { width: 1, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 2,
  },
  letterText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
  },
});
